### ISSUE TITLE
Optional: use different formatting to write css blocks

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/elena_task#11]
In future projects:

Don't do like this:
```css
* 
{
 box-sizing: border-box;
}
```

Do like this:
```css
* {
 box-sizing: border-box;
}
```
